name = "Void"
license = "MIT"
licenselink = "https://github.com/MrNanko/void/blob/master/LICENSE"
description = "A clean, minimalist Hugo theme with elegant typography and modern design"
homepage = "https://github.com/MrNanko/void"
tags = ["blog", "minimal", "clean", "typography", "responsive", "modern"]
features = ["responsive", "syntax-highlighting", "pagination", "archives", "tags", "categories"]
min_version = "0.74.0"

[author]
  name = "Mr Nanko"
  homepage = "https://yourwebsite.com"